server:
  port: 8080
  
#DB Info
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/doowarf?allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: doowarf
    password: doowarf

#Mybatis location setting
mybatis: 
  mapper-locations: mapper/**/*.xml